version: 2
jobs:
  build:
    working_directory: ~/rottnote
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: npm-install-react-app-dependencies
          working_directory: ~/rottnote/client
          command: npm install
      - run:
          name: npm-build-react-app
          working_directory: ~/rottnote/client
          command: npm run build
      - run:
          name: npm-install-nodejs-app-dependencies
          command: npm install
      - run: echo "TODO App deployment..."
