version: 2
jobs:
  build:
    working_directory: ~/rottnote
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: npm-install-react-app-dependencies
          working_directory: ~/rottnote/client
          command: npm install
      - run:
          name: npm-build-react-app
          working_directory: ~/rottnote/client
          command: npm run build
      - run:
          name: npm-deploy-to-now
          command: now -e NODE_ENV=production -e DB_URI=${DB_URI} -t ${NOW_TOKEN} alias rottnote
