version: 2
jobs:
  build:
    working_directory: ~/rottnote
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: Install Zeit now
          command: sudo npm install now --global
      - run:
          name: Install Dependencies of rottnote React App
          working_directory: ~/rottnote/client
          command: npm install
      - run:
          name: Build rottnote React App
          working_directory: ~/rottnote/client
          command: npm run build
      - run:
          name: Deploy rottnote Using Zeit now
          command: now -e NODE_ENV=production -e DB_URI=${DB_URI} -t ${NOW_TOKEN}
      - run:
          name: Echo NOW_URL
          command: echo $${NOW_URL}
      - run:
          name: Publish rottnote to url https://rottnote.now.sh
          command: now alias ${NOW_URL} rottnote -t ${NOW_TOKEN}
